//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEmployee
    {
        public int eId { get; set; }
        public string Title { get; set; }
        [Required(ErrorMessage = "It cannot remain empty")]
        public string eName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "It cannot remain empty")]
        public string eGender { get; set; }
        public string PhoneNo { get; set; }
        [Required(ErrorMessage = "It cannot remain empty")]
        public Nullable<int> positionId { get; set; }
        public string eImage { get; set; }
    
        public virtual tblPosition tblPosition { get; set; }
    }
}
