//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEpersonla
    {
        public int eId { get; set; }
        public string eTitle { get; set; }
        public string eName { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime eDob { get; set; }
        public string eGender { get; set; }
        public string eNationalIdNo { get; set; }
        public string ePhoneNo { get; set; }
        public string eEmail { get; set; }
        public string eMeritals { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime eJoinDate { get; set; }
        public string eImage { get; set; }
    }
}
